/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import classes.AgileLogger;
import dal.DataConnect;
import java.io.BufferedOutputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sheldon
 */

public class Agility extends javax.swing.JFrame {
public static final Logger LOGGER = Logger.getLogger(DataConnect.class.getName());
Logger agility = AgileLogger.loggerHandler(LOGGER);

    /**
     * Creates new form Agility
     */
    public Agility() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        goalsMenu = new javax.swing.JMenu();
        setGoalMenuItem1 = new javax.swing.JMenuItem();
        viewGoalMenuItem = new javax.swing.JMenuItem();
        todoMenu = new javax.swing.JMenu();
        newTodoMenuItem = new javax.swing.JMenuItem();
        viewTodoMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        configMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agility");

        desktopPane.setLayout(null);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        goalsMenu.setMnemonic('g');
        goalsMenu.setText("Goals");

        setGoalMenuItem1.setMnemonic('s');
        setGoalMenuItem1.setText("Set a Goal");
        setGoalMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setGoalMenuItem1ActionPerformed(evt);
            }
        });
        goalsMenu.add(setGoalMenuItem1);

        viewGoalMenuItem.setMnemonic('v');
        viewGoalMenuItem.setText("View Goals");
        goalsMenu.add(viewGoalMenuItem);

        menuBar.add(goalsMenu);

        todoMenu.setMnemonic('t');
        todoMenu.setText("To do..");

        newTodoMenuItem.setMnemonic('n');
        newTodoMenuItem.setText("New todo");
        newTodoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTodoMenuItemActionPerformed(evt);
            }
        });
        todoMenu.add(newTodoMenuItem);

        viewTodoMenuItem.setMnemonic('v');
        viewTodoMenuItem.setText("View todos");
        todoMenu.add(viewTodoMenuItem);

        menuBar.add(todoMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        configMenuItem.setMnemonic('c');
        configMenuItem.setText("Get Config!");
        configMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(configMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void setGoalMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setGoalMenuItem1ActionPerformed
        GoalMaker gm = new GoalMaker();
        gm.setVisible(true);
        desktopPane.add(gm);
    }//GEN-LAST:event_setGoalMenuItem1ActionPerformed

    private void newTodoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTodoMenuItemActionPerformed
        TodoMaker todo = new TodoMaker();
        todo.setVisible(true);
        desktopPane.add(todo);
    }//GEN-LAST:event_newTodoMenuItemActionPerformed

    private void configMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configMenuItemActionPerformed
        try{
            Socket socket = new Socket("127.0.0.1", 9615);
            byte[] fileToReceive = new byte[8000000];
            InputStream inputStream = socket.getInputStream();
            FileOutputStream fileOutputStream = new FileOutputStream("config/dbconfig.xml");
            BufferedOutputStream bufferedOutputStream = new BufferedOutputStream(fileOutputStream);
            int bytesReadFromFile = inputStream.read(fileToReceive, 0, fileToReceive.length);
            bufferedOutputStream.write(fileToReceive, 0, bytesReadFromFile);
            bufferedOutputStream.flush();
            JOptionPane.showMessageDialog(this, "Configuration Downloaded Successfully " + bytesReadFromFile + " bytes");
        }catch(Exception ex) {          
            agility.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_configMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agility().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem configMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu goalsMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newTodoMenuItem;
    private javax.swing.JMenuItem setGoalMenuItem1;
    private javax.swing.JMenu todoMenu;
    private javax.swing.JMenuItem viewGoalMenuItem;
    private javax.swing.JMenuItem viewTodoMenuItem;
    // End of variables declaration//GEN-END:variables

}
