/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.Goal;
import entities.Task;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author sheldon
 */
public class GoalMaker extends javax.swing.JInternalFrame {

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("AgilityPU");
    EntityManager em = emf.createEntityManager();
    Goal goal = new Goal();
    Task task = new Task();
    List<Task> td = new ArrayList();
    Date oDate;
    String goalDate;
    DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form GoalMaker
     */
    public GoalMaker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wizardContainer = new javax.swing.JPanel();
        goalNamePanel = new javax.swing.JPanel();
        introLabel = new javax.swing.JLabel();
        goalNameTitleLabel = new javax.swing.JLabel();
        goalNameTextBox = new javax.swing.JTextField();
        panelTitleLabel = new javax.swing.JLabel();
        namePanelContinueButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        goalDescriptionPanel = new javax.swing.JPanel();
        descriptionLabel = new javax.swing.JLabel();
        descriptionLabelTrailing = new javax.swing.JLabel();
        goalDescriptionLabel = new javax.swing.JLabel();
        descriptionScrollPane = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        goalPanelTitleLabel = new javax.swing.JLabel();
        descPanelBackButton = new javax.swing.JButton();
        descPanelContinueButton = new javax.swing.JButton();
        descPanelCancelButton = new javax.swing.JButton();
        goalDatePanel = new javax.swing.JPanel();
        dateInstructionLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        goalDatePicker = new org.jdesktop.swingx.JXDatePicker();
        finalInstructionLabel = new javax.swing.JLabel();
        finalTrailingLabel = new javax.swing.JLabel();
        dateBackButton = new javax.swing.JButton();
        datePanelContinueButton = new javax.swing.JButton();
        datePanelTitleLabel = new javax.swing.JLabel();
        datePanelCancelButton = new javax.swing.JButton();
        taskPanel = new javax.swing.JPanel();
        taskPanelCancelButton = new javax.swing.JButton();
        taskPanelBackButton = new javax.swing.JButton();
        taskPanelSetGoalButton = new javax.swing.JButton();
        datePanelTitleLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        taskGoalLabel = new javax.swing.JLabel();
        taskTextField = new javax.swing.JTextField();
        addTaskButton = new javax.swing.JButton();
        deleteTaskButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taskTable = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Goal Maker Wizard"); // NOI18N

        wizardContainer.setLayout(new java.awt.CardLayout());

        goalNamePanel.setMinimumSize(new java.awt.Dimension(800, 600));
        goalNamePanel.setPreferredSize(new java.awt.Dimension(800, 600));
        goalNamePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        introLabel.setText("Welcome to the Agility's Simple Goal Maker. First thing's first; fill out the form below then we'll add some tasks");
        goalNamePanel.add(introLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 251, -1, -1));

        goalNameTitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        goalNameTitleLabel.setText("Give your goal a name");
        goalNamePanel.add(goalNameTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 279, -1, -1));

        goalNameTextBox.setToolTipText("It's best to keep this short. ");
        goalNamePanel.add(goalNameTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 279, 509, -1));

        panelTitleLabel.setFont(new java.awt.Font("Anders", 1, 36)); // NOI18N
        panelTitleLabel.setText("Agility Goal Maker");
        goalNamePanel.add(panelTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 0, -1, -1));

        namePanelContinueButton.setText("Continue");
        namePanelContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namePanelContinueButtonActionPerformed(evt);
            }
        });
        goalNamePanel.add(namePanelContinueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, -1, -1));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        goalNamePanel.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, -1, -1));

        wizardContainer.add(goalNamePanel, "card2");

        goalDescriptionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descriptionLabel.setText("Try to describe what you plan to accomplish. This is optional but it's a really good practice as it helps you think");
        goalDescriptionPanel.add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 208, -1, -1));

        descriptionLabelTrailing.setText("up the tasks you'll need to add later on.");
        goalDescriptionPanel.add(descriptionLabelTrailing, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 230, -1, -1));

        goalDescriptionLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        goalDescriptionLabel.setText("Describe your goal");
        goalDescriptionPanel.add(goalDescriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 264, -1, -1));

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionScrollPane.setViewportView(descriptionTextArea);

        goalDescriptionPanel.add(descriptionScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 264, 536, 128));

        goalPanelTitleLabel.setFont(new java.awt.Font("Anders", 1, 36)); // NOI18N
        goalPanelTitleLabel.setText("Agility Goal Maker");
        goalPanelTitleLabel.setAlignmentY(0.0F);
        goalDescriptionPanel.add(goalPanelTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        descPanelBackButton.setText("Go Back");
        descPanelBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descPanelBackButtonActionPerformed(evt);
            }
        });
        goalDescriptionPanel.add(descPanelBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, -1, -1));

        descPanelContinueButton.setText("Continue");
        descPanelContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descPanelContinueButtonActionPerformed(evt);
            }
        });
        goalDescriptionPanel.add(descPanelContinueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, -1, -1));

        descPanelCancelButton.setText("Cancel");
        descPanelCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descPanelCancelButtonActionPerformed(evt);
            }
        });
        goalDescriptionPanel.add(descPanelCancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, -1, -1));

        wizardContainer.add(goalDescriptionPanel, "card3");

        goalDatePanel.setPreferredSize(new java.awt.Dimension(800, 600));
        goalDatePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateInstructionLabel.setText("You're gonna need to have some date in mind as to when you want to accomplish this goal. We'll set that next");
        goalDatePanel.add(dateInstructionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 242, -1, -1));

        dateLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        dateLabel.setText("Set a date");
        goalDatePanel.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 281, -1, -1));

        goalDatePicker.setLinkPanel(null);
        goalDatePicker.setOpaque(true);
        goalDatePanel.add(goalDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 276, -1, -1));

        finalInstructionLabel.setText("Great! We're well on our way. Next we'll add some tasks. Go ahead and give what we have there a good look over");
        goalDatePanel.add(finalInstructionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 319, -1, -1));

        finalTrailingLabel.setText("When you're comfortable with what you see here, go ahead and click continue.");
        goalDatePanel.add(finalTrailingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 341, -1, -1));

        dateBackButton.setText("Go Back");
        dateBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateBackButtonActionPerformed(evt);
            }
        });
        goalDatePanel.add(dateBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, -1, -1));

        datePanelContinueButton.setText("Continue");
        datePanelContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datePanelContinueButtonActionPerformed(evt);
            }
        });
        goalDatePanel.add(datePanelContinueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, -1, -1));

        datePanelTitleLabel.setFont(new java.awt.Font("Anders", 1, 36)); // NOI18N
        datePanelTitleLabel.setText("Agility Goal Maker");
        goalDatePanel.add(datePanelTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        datePanelCancelButton.setText("Cancel");
        datePanelCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datePanelCancelButtonActionPerformed(evt);
            }
        });
        goalDatePanel.add(datePanelCancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, -1, -1));

        wizardContainer.add(goalDatePanel, "card4");

        taskPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        taskPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        taskPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                taskPanelFocusGained(evt);
            }
        });
        taskPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taskPanelCancelButton.setText("Cancel");
        taskPanelCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskPanelCancelButtonActionPerformed(evt);
            }
        });
        taskPanel.add(taskPanelCancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, -1, -1));

        taskPanelBackButton.setText("Go Back");
        taskPanelBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskPanelBackButtonActionPerformed(evt);
            }
        });
        taskPanel.add(taskPanelBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, -1, -1));

        taskPanelSetGoalButton.setText("Set Goal!");
        taskPanelSetGoalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskPanelSetGoalButtonActionPerformed(evt);
            }
        });
        taskPanel.add(taskPanelSetGoalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, -1, -1));

        datePanelTitleLabel1.setFont(new java.awt.Font("Anders", 1, 36)); // NOI18N
        datePanelTitleLabel1.setText("Agility Goal Maker");
        taskPanel.add(datePanelTitleLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 0, -1, -1));

        jLabel1.setText("It's time to add some tasks. A goal's not a goal if you don't have steps to accomplish it! ");
        taskPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel2.setText("Task to accomplish");
        taskPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 121, -1, -1));

        taskGoalLabel.setText("Goal");
        taskPanel.add(taskGoalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 121, -1, -1));
        taskPanel.add(taskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 143, 658, -1));

        addTaskButton.setText("+");
        addTaskButton.setToolTipText("Adds a Task");
        addTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskButtonActionPerformed(evt);
            }
        });
        taskPanel.add(addTaskButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 143, 42, -1));

        deleteTaskButton.setText("-");
        deleteTaskButton.setToolTipText("Removes a Task");
        deleteTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTaskButtonActionPerformed(evt);
            }
        });
        taskPanel.add(deleteTaskButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 143, 42, -1));

        taskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tasks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        taskTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taskTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taskTable);

        taskPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 753, 329));

        wizardContainer.add(taskPanel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wizardContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wizardContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namePanelContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namePanelContinueButtonActionPerformed
        if (goalNameTextBox.getText().trim().isEmpty() == false) {
            wizardContainer.removeAll();
            wizardContainer.add(goalDescriptionPanel);
            wizardContainer.repaint();
            wizardContainer.revalidate();
        } else {
            JOptionPane.showMessageDialog(rootPane, "You need to think up an name for your goal first!", "Name your goal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_namePanelContinueButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void descPanelContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descPanelContinueButtonActionPerformed
        wizardContainer.removeAll();
        wizardContainer.add(goalDatePanel);
        wizardContainer.repaint();
        wizardContainer.revalidate();
    }//GEN-LAST:event_descPanelContinueButtonActionPerformed

    private void descPanelBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descPanelBackButtonActionPerformed
        wizardContainer.removeAll();
        wizardContainer.add(goalNamePanel);
        wizardContainer.repaint();
        wizardContainer.revalidate();
    }//GEN-LAST:event_descPanelBackButtonActionPerformed

    private void dateBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateBackButtonActionPerformed
        wizardContainer.removeAll();
        wizardContainer.add(goalDescriptionPanel);
        wizardContainer.repaint();
        wizardContainer.revalidate();
    }//GEN-LAST:event_dateBackButtonActionPerformed

    private void taskPanelBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskPanelBackButtonActionPerformed
        wizardContainer.removeAll();
        wizardContainer.add(goalDatePanel);
        wizardContainer.repaint();
        wizardContainer.revalidate();
    }//GEN-LAST:event_taskPanelBackButtonActionPerformed

    private void taskPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taskPanelFocusGained
        taskGoalLabel.setText(goalNameTextBox.getText());
    }//GEN-LAST:event_taskPanelFocusGained

    private void addTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskButtonActionPerformed
        task.setName(taskTextField.getText());
        task.setGoal(goal);
        task.setStatus('o');
        task.setCreated(new java.sql.Timestamp(new java.util.Date().getTime()));
        td.add(task);
        goal.setTask(td);
        
        DefaultTableModel model = (DefaultTableModel)taskTable.getModel();
        Object[] row = new Object[1];
        for (int i=0; i<td.size(); i++){
            row[0] = td.get(i).getName();
            model.addRow(row);
        }
    }//GEN-LAST:event_addTaskButtonActionPerformed

    private void deleteTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTaskButtonActionPerformed
        if (taskTable.getSelectedRow() != -1) {
            td.remove(taskTable.getSelectedRow());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ah! You gotta select the one you want to remove first.", "Looks like you forgot something", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteTaskButtonActionPerformed

    private void taskPanelCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskPanelCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_taskPanelCancelButtonActionPerformed

    private void datePanelContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datePanelContinueButtonActionPerformed

        if (goalDatePicker.getDate() != null) {
            oDate = goalDatePicker.getDate();
            goalDate = oDateFormat.format(oDate);
            goal.setDeadline(java.sql.Date.valueOf(LocalDate.parse(goalDate)));
            wizardContainer.removeAll();
            wizardContainer.add(taskPanel);
            wizardContainer.repaint();
            wizardContainer.revalidate();
            taskGoalLabel.setText(goalNameTextBox.getText().trim());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Sorry to break it to you like this but a goal without a date is a wish!", "Give your goal a date", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_datePanelContinueButtonActionPerformed

    private void taskPanelSetGoalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskPanelSetGoalButtonActionPerformed
        goal.setName(goalNameTextBox.getText());
        //Since goal description field is optional,
        //this checks to see if a description was entered by the user
        //if not it puts a placeholder into the database
        if (descriptionTextArea.getText().trim().isEmpty()) {
            goal.setDescription("This goal was not described...");
        } else {
            goal.setDescription(descriptionTextArea.getText().trim());
        }
        
        goal.setCreated(new java.sql.Timestamp(new java.util.Date().getTime()));
        goal.setStatus('o');
        goal.setTypeid('g');
        em.getTransaction().begin();
        em.persist(goal);
        em.getTransaction().commit();
        
        JOptionPane.showMessageDialog(this, "You did it! You made a goal! Let's try our best to keep it!");
        this.dispose();

    }//GEN-LAST:event_taskPanelSetGoalButtonActionPerformed

    private void datePanelCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datePanelCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_datePanelCancelButtonActionPerformed

    private void descPanelCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descPanelCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_descPanelCancelButtonActionPerformed

    private void taskTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskTableMouseClicked
        int i = taskTable.getSelectedRow();
        TableModel model = taskTable.getModel();
        taskTextField.setText(model.getValueAt(i, 0).toString());
    }//GEN-LAST:event_taskTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTaskButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton dateBackButton;
    private javax.swing.JLabel dateInstructionLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton datePanelCancelButton;
    private javax.swing.JButton datePanelContinueButton;
    private javax.swing.JLabel datePanelTitleLabel;
    private javax.swing.JLabel datePanelTitleLabel1;
    private javax.swing.JButton deleteTaskButton;
    private javax.swing.JButton descPanelBackButton;
    private javax.swing.JButton descPanelCancelButton;
    private javax.swing.JButton descPanelContinueButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel descriptionLabelTrailing;
    private javax.swing.JScrollPane descriptionScrollPane;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel finalInstructionLabel;
    private javax.swing.JLabel finalTrailingLabel;
    private javax.swing.JPanel goalDatePanel;
    private org.jdesktop.swingx.JXDatePicker goalDatePicker;
    private javax.swing.JLabel goalDescriptionLabel;
    private javax.swing.JPanel goalDescriptionPanel;
    private javax.swing.JPanel goalNamePanel;
    private javax.swing.JTextField goalNameTextBox;
    private javax.swing.JLabel goalNameTitleLabel;
    private javax.swing.JLabel goalPanelTitleLabel;
    private javax.swing.JLabel introLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton namePanelContinueButton;
    private javax.swing.JLabel panelTitleLabel;
    private javax.swing.JLabel taskGoalLabel;
    private javax.swing.JPanel taskPanel;
    private javax.swing.JButton taskPanelBackButton;
    private javax.swing.JButton taskPanelCancelButton;
    private javax.swing.JButton taskPanelSetGoalButton;
    private javax.swing.JTable taskTable;
    private javax.swing.JTextField taskTextField;
    private javax.swing.JPanel wizardContainer;
    // End of variables declaration//GEN-END:variables
}
