/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author sheldon
 */
public class GoalViewer extends javax.swing.JInternalFrame {
//ArrayList<Todo> todo = dc.getToDoList();
//Todo td = new Todo();
    /**
     * Creates new form GoalViewer
     */
    public GoalViewer() {
        initComponents();
    }
    
     public void progress(){
//        float progress = (tasksDone/tasksCreated)*100;
//        todoProgressBar.setValue((int)progress);
//        taskNumLabel.setText(String.valueOf(tasksCreated));
    }
//    float tasksCreated = dc.recordCount("SELECT COUNT(*) FROM \"public\".goal WHERE typeid = 't';");
//    float tasksDone = dc.recordCount("SELECT COUNT(*) FROM \"public\".goal WHERE typeid = 't' and status = 'c';");
    
    /**
     * Display TODOs in JTable
     */
    public void populateTodo() {
//        DefaultTableModel model = (DefaultTableModel)todoTable.getModel();
//        Object[] row = new Object[2];
//        for (int i=0;i<todo.size();i++) {
//            row[0] = todo.get(i).getName(); 
//            row[1] = todo.get(i).getId();
//            model.addRow(row);
//        }
//        
    }
    /**
     * Refresh Table Data
     */
    public void refresh(){
        DefaultTableModel model = (DefaultTableModel)todoTable.getModel();
        model.setRowCount(0);
        populateTodo();
        
        todoTextField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskPanel = new javax.swing.JPanel();
        todoTitleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        todoTextField = new javax.swing.JTextField();
        clearTaskButton = new javax.swing.JButton();
        addTaskButton = new javax.swing.JButton();
        removeTaskButton = new javax.swing.JButton();
        todoScrollPane = new javax.swing.JScrollPane();
        todoTable = new javax.swing.JTable();
        todoProgressBar = new javax.swing.JProgressBar();
        taskNumLabel = new javax.swing.JLabel();

        taskPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        taskPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        taskPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                taskPanelFocusGained(evt);
            }
        });
        taskPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        todoTitleLabel.setFont(new java.awt.Font("Anders", 1, 36)); // NOI18N
        todoTitleLabel.setText("Agility GOAL");
        taskPanel.add(todoTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        jLabel1.setText("Goal:");
        taskPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel2.setText("Total Steps:");
        taskPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));
        taskPanel.add(todoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 590, -1));

        clearTaskButton.setText("^");
        clearTaskButton.setToolTipText("Adds a Task");
        clearTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTaskButtonActionPerformed(evt);
            }
        });
        taskPanel.add(clearTaskButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 42, -1));

        addTaskButton.setText("+");
        addTaskButton.setToolTipText("Adds a Task");
        addTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskButtonActionPerformed(evt);
            }
        });
        taskPanel.add(addTaskButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 42, -1));

        removeTaskButton.setText("-");
        removeTaskButton.setToolTipText("Removes a Task");
        removeTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTaskButtonActionPerformed(evt);
            }
        });
        taskPanel.add(removeTaskButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 42, -1));

        todoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tasks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        todoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                todoTableMouseClicked(evt);
            }
        });
        todoScrollPane.setViewportView(todoTable);

        taskPanel.add(todoScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 753, 329));

        todoProgressBar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                todoProgressBarPropertyChange(evt);
            }
        });
        taskPanel.add(todoProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 700, -1));

        taskNumLabel.setText("No tasks created, create one below!");
        taskPanel.add(taskNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(taskPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(taskPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTaskButtonActionPerformed
//        dc.completeToDo(todoTextField.getText());

        DefaultTableModel model = (DefaultTableModel)todoTable.getModel();
        model.setRowCount(0);
        refresh();
        progress();
    }//GEN-LAST:event_clearTaskButtonActionPerformed

    private void addTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskButtonActionPerformed
        String in = todoTextField.getText();

        refresh();
        progress();
    }//GEN-LAST:event_addTaskButtonActionPerformed

    private void removeTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTaskButtonActionPerformed
        refresh();
    }//GEN-LAST:event_removeTaskButtonActionPerformed

    private void todoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todoTableMouseClicked
        //Make todo editable on click
        int i = todoTable.getSelectedRow();
        TableModel model = todoTable.getModel();
        todoTextField.setText(model.getValueAt(i, 0).toString());
    }//GEN-LAST:event_todoTableMouseClicked

    private void todoProgressBarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_todoProgressBarPropertyChange
        progress();
    }//GEN-LAST:event_todoProgressBarPropertyChange

    private void taskPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taskPanelFocusGained

    }//GEN-LAST:event_taskPanelFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTaskButton;
    private javax.swing.JButton clearTaskButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton removeTaskButton;
    private javax.swing.JLabel taskNumLabel;
    private javax.swing.JPanel taskPanel;
    private javax.swing.JProgressBar todoProgressBar;
    private javax.swing.JScrollPane todoScrollPane;
    private javax.swing.JTable todoTable;
    private javax.swing.JTextField todoTextField;
    private javax.swing.JLabel todoTitleLabel;
    // End of variables declaration//GEN-END:variables
}
